import { StyleSheet } from 'react-native';
const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#1a3e1a',
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  container: {
    flex: 1,
    backgroundColor: '#1a3e1a',
    padding: 20,
    paddingTop: 20,
  },
  header: {
    alignItems: 'center',
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#33cc33',
    letterSpacing: 1,
  },
  pontosContainer: {
    backgroundColor: 'rgba(51, 204, 51, 0.15)',
    padding: 15,
    borderRadius: 10,
    marginBottom: 25,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(51, 204, 51, 0.3)',
  },
  pontosLabel: {
    color: '#33cc33',
    fontSize: 14,
    letterSpacing: 1,
  },
  pontosValue: {
    color: '#fff',
    fontSize: 36,
    fontWeight: 'bold',
    marginTop: 5,
  },
  bettingArea: {
    backgroundColor: 'rgba(30, 80, 40, 0.7)',
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(51, 204, 51, 0.2)',
  },
  sectionTitle: {
    color: '#33cc33',
    fontSize: 16,
    marginBottom: 15,
    textAlign: 'center',
    letterSpacing: 1,
  },
  numbersGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: 20,
  },
  numberChip: {
    width: 45,
    height: 45,
    borderRadius: 23,
    margin: 6,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 3,
  },
  redChip: {
    backgroundColor: '#e84118',
  },
  blackChip: {
    backgroundColor: '#2f3640',
  },
  selectedChip: {
    borderWidth: 3,
    borderColor: '#33cc33',
    shadowColor: '#33cc33',
    shadowRadius: 10,
  },
  chipButton: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
  },
  chipText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
  },
  colorSelection: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 10,
  },
  colorChip: {
    width: 110,
    height: 45,
    borderRadius: 23,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  redChipBig: {
    backgroundColor: '#e84118',
  },
  blackChipBig: {
    backgroundColor: '#2f3640',
  },
  selectedColorChip: {
    borderWidth: 3,
    borderColor: '#33cc33',
  },
  colorText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
    letterSpacing: 1,
  },
  spinButtonContainer: {
    alignItems: 'center',
    marginVertical: 20,
  },
  spinButton: {
    width: 220,
    borderRadius: 25,
    overflow: 'hidden',
    elevation: 10,
  },
  spinButtonGradient: {
    paddingVertical: 12,
    paddingHorizontal: 25,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#33cc33',
  },
  spinButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    letterSpacing: 1,
  },
  resultContainer: {
    backgroundColor: 'rgba(30, 80, 40, 0.8)',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
    borderWidth: 1,
    borderColor: 'rgba(51, 204, 51, 0.3)',
    marginBottom: 30,
  },
  resultTitle: {
    color: '#33cc33',
    fontSize: 14,
    marginBottom: 10,
  },
  resultBall: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    marginBottom: 10,
  },
  resultNumber: {
    color: '#fff',
    fontSize: 22,
    fontWeight: 'bold',
  },
  resultText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
});
export {styles}